### ISSUE TITLE
Jlcpcb order help

### ISSUE THREAD

**Issue by how-eee** [spoter368/os3m-hardware#18]
Could you please describe what options we need there. 
And how to order assembled pcb. 
![Screenshot_20240504-232333_Chrome](https://github.com/spoter368/os3m-hardware/assets/3368649/e2e73a60-642e-4791-b4da-55de9475b0fd)

**Comment by kamilkara** [comment]
Great project! Thanks for sharing this with the community. 

I also would like to know how to order assembled pcb. Do you also have a plan for updating soon regarding #19, please?

Thanks a lot.

**Comment by spoter368** [comment]
Hi @kamilkara , you can simply use the default settings with the exception of making it a 4 layer board.

I will update and resolve #19 soon
