### ISSUE TITLE
JLCPCB parts out of stock

### ISSUE THREAD

**Issue by Nanotech45** [spoter368/os3m-hardware#19]
Upon going to order the assembled PCB via JLCPCB, they notified me that two components are out of stock:

SW1 - SW_Push - Button Switch
X1 - XTAL_40MHz - 40 MHz Oscillator

The button switch looks like it will be easy to source an alternative. After attempting to pre-order the 40 MHz oscillator, they informed me that the manufacturer has discontinued that part number. It looks like a replacement part will need to be sourced. 

@spoter368

**Comment by spoter368** [comment]
I haven't vetted the components myself, but going off the datasheet, the parts I just pushed to the BOM should work
