### ISSUE TITLE
Drivers?

### ISSUE THREAD

**Issue by krummrey** [spoter368/os3m-hardware#2]
I'd love to build one, but it seems that the driver side for OSX is missing, right?
Hopefully the project gains some momentum and some smart people come on board and complement the project to make it a usable solution.
Great start!

**Comment by spoter368** [comment]
The driver is builtin to the firmware (available at https://github.com/spoter368/os3m-firmware). It is a USB HID device, which is supported by all modern OSs. The software script I wrote (here: https://github.com/spoter368/os3m-software) is currently Windows only, but all that does is convert the HID data (which any OS can receive) into solidworks API calls. It will become more advanced in the future though.
