### ISSUE TITLE
Releases section and file order

### ISSUE THREAD

**Issue by Liam-Newell** [spoter368/os3m-hardware#7]
Hey I was just confused for a minute why the gerbers file wasn't in the sub folder mentioned in the readme then got more confused why the zip rev file wasn't a gerbers file. Took me a minute to understand where your PCB spec was.

Would recommend a small modification to where you're storing files and the file location in the READ.md **releases would make this easier** because you can just put all the required files in the file section of the readme.

**Comment by spoter368** [comment]
I'm not sure what you mean... the readme says "Gerbers can be found in the os3m-gerbers folder" and if you go to "PCB/os3m-gerbers" that is where the gerbers are. I make no mention of zip files in the readme; they are only there so I can remember the state of the project when I released it (i.e. releases but before this project was uploaded to GitHub). Should there be another revision of the mouse, I'm open to using the releases feature of GitHub.
